variable "project_id" {}
variable "region" {}
variable "name" {}
variable "description" {}
variable "network" {}
variable "subnetwork" {}
variable "network_project_id" {}
variable "regional" {}
variable "zones" {}
variable "kubernetes_version" {}
variable "datapath_provider" {}
variable "networking_mode" {}
variable "ip_range_pods" {}
variable "ip_range_services" {}
variable "master_ipv4_cidr_block" {}
variable "deletion_protection" {}
variable "remove_default_node_pool" {}
variable "node_pool_name" {}
variable "machine_type" {}
variable "image_type" {}
variable "local_ssd_count" {}
variable "disk_size_gb" {}
variable "disk_type" {}
variable "preemptible" {}
variable "node_locations" {}
variable "autoscaling" {}
variable "min_count" {}
variable "max_count" {}
variable "initial_node_count" {}
variable "max_pods_per_node" {}
variable "node_metadata" {}
variable "enable_private_nodes" {}
